### ISSUE TITLE
[E-Commerce]: Implement Facebook login feature

### ISSUE THREAD

**Issue by RailKill** [harytan/Project_LabVamor#10]
Maybe can just use some free plugins:
https://wordpress.org/plugins/accesspress-social-login-lite/

There's a premium full-featured one that can even generate awesome reports, but of course we won't be using this. Just letting everyone know that it's cool: http://www.woothemes.com/products/woocommerce-social-login/

**Comment by harytan** [comment]
Proceed. Implement this in mobile as well.

**Comment by RailKill** [comment]
Since the implementation of #5, UserPro plugin comes with social logins. Once we put in the Facebook Dev App ID into UserPro, the Facebook app itself needs to allow the domain to perform transactions. We just have to do a quick test on this when we migrate to the lab-vamor.com server.

**Comment by RailKill** [comment]
When using the Facebook Login button in Sample-CORS-Client (which calls login-fb.php), it now creates a session (logs the user in) and returns the session ID.

**Comment by harytan** [comment]
Solved
