### ISSUE TITLE
[Mobile Apps]: Mobile Apps Development Strategy

### ISSUE THREAD

**Issue by harytan** [harytan/Project_LabVamor#11]
As discussed that day, mobile app layout should be different with mobile browsing.
@los3rz please wrote down your researches and suggestions in detail over here so that we could come out with a proper strategy plan for mobile apps development.

**Comment by RailKill** [comment]
When coming up with this strategy, please also refer to my findings on REST API #9

**Comment by harytan** [comment]
Solved. Will implement API from e-commerce site for mobile apps to call.
