### ISSUE TITLE
Address database conflicts

### ISSUE THREAD

**Issue by RailKill** [harytan/Project_LabVamor#3]
Current Process
----------------------
We make a dump (or backup) of the database every time. To revert changes in data, we can import the old dumps, etc. To get the latest data, we import the latest dump. This is good, but there is still a database conflict problem, which is the nature of working with something like WordPress.

Problematic Scenario
-------------------------------
When multiple devs are working at the same time, database changes will conflict. Changes in Page content is one example, basically anything that is stored in the database will have this scenario:

1. Hary makes changes that affects database.
2. Nic makes changes that affects database.
3. Hary commits and pushes to master.
4. Nic is out of date.
5. Nic pulls the latest changes. Code is now up to date.
6. Nic realizes database is not up to date.
7. If Nic imports, Nic loses all his database changes.
8. If Nic does not import, Nic works with an out-of-date database which may cause problems (e.g: when plugins add their own data and everyone's data is different).

Suggested Resolution
------------------------------------
Use one remote database that you all connect to with lots of backups.

**Reference:**
http://wordpress.stackexchange.com/questions/12719/multiple-developers-editors-working-on-a-site-in-progress

**Comment by los3rz** [comment]
We can try to use webhost free mysql hosting solely for development purpose. 

http://www.000webhost.com/free-mysql-hosting

**Comment by RailKill** [comment]
Resolved by changing wp-config.php to point to mojo10.synology.me, so that all database changes will be on my server.
