### ISSUE TITLE
Decide on hosting plan

### ISSUE THREAD

**Issue by RailKill** [harytan/Project_LabVamor#8]
@harytan Exabytes doesn't seem very attractive, but here it is: http://www.exabytes.my/web-hosting/small-business-hosting/ - suggest to go for EBiz Plus plan @ RM285/year

Domain is separate. Price is good, around RM40/year. http://www.exabytes.my/services/domain/

**Comment by harytan** [comment]
Okay, thanks Nicholas. I have just talked with Kenneth, he said he would be able to get the domain and hosting back by next Monday and Tuesday. This will be our back up plan.
