### ISSUE TITLE
Implement WooCommerce REST API into Android app

### ISSUE THREAD

**Issue by RailKill** [harytan/Project_LabVamor#9]
1. Enable API and generate keys: https://docs.woothemes.com/document/woocommerce-rest-api/
2. Refer to API docs: http://woothemes.github.io/woocommerce-rest-api-docs
3. Build a simple Android app to fetch all products from site. Use PhoneGap or something, make things easier.
4. Display it in app.

**Comment by RailKill** [comment]
@harytan @los3rz [Initial investigation](https://github.com/woothemes/woocommerce/issues/6126) suggests that allowing users to provide username/password off-site is bad practice and is a security risk, which is why there is no API to allow front-end mobile apps to submit login details.

The WooCommerce REST API currently works by first generating the OAuth keys. Once authenticated using these keys, you can either have Read, Write or Read/Write access to the entire WooCommerce (not by user). Because of this, we cannot directly use the REST API for users to make orders or login. I've given a general overview of currently available approaches below. Needless to say, method 1 is still the easier one.

------------------------------------------------------------------------------------------------------------------------------

Method 1: WebView Injection
----------------------------------------------------------------
1. Do most of the UI, add some buttons, etc. outside of the WebView.
2. Whenever there is a function that requires connection to the website, we create a WebView or iframe instance. WebView can be used to display certain parts of the website or certain HTML elements. So when it comes to login, we have a WebView that displays login fields. When it comes to products, we have a WebView that displays products.
3. If we really need to modify the WebView contents, we can hack it in. (e.g: [Android](http://stackoverflow.com/questions/17209826/dynamically-changing-css-values-in-a-webview-without-reloading-android))

Method 2: Delegation + OAuth
---------------------------------------
This delegation is basically how my Lowyat Bumper app works.
1. The login screen in the app will delegate to the website. This means that we present the username and password fields UI in the app, but what actually happens behind-the-scenes is the app will load the website like a browser and key in the username/password into the website, then click Submit. If success, we get the session and the user is logged in.
2. The app will use the OAuth key with Read access. Regardless of which user logged in, the posts and products are public so we can use the REST API to just display everything.
3. When the user needs to make an order, we delegate it to the website again. Using the session we've just created, we will simulate clicking the Checkout button, etc.

**Comment by los3rz** [comment]
@RailKill so do you mean that only method 2 will be able to work? From what i know about phonegap now is that the whole application will be a webview. Its like creating a html site and it will be displayed on the webview of the application. So to call your rest api or anything, I will be able to use a normal ajax call or any post/get calls to any of the link that you exposed through woocommerce. Correct me if i am wrong.
This is so far my understanding on how phone gap will be able to communicate with woocommerce. You can imagine like creating an external html based website but calling exposed woocommerce functions.

**Comment by RailKill** [comment]
Yes, likely method 2. Yes, we are creating somewhat of an external website calling exposed functions, but these functions are unsafe. As mentioned, the REST API provided by WooCommerce is at the admin level and will be unsafe if users can use this API through our app.

There is no login API. Method 2 for example, builds the HTTP request and sends it to the site, like a browser would when submitting a login form. I will try to demonstrate this, need a few days time to experiment. Meanwhile, you could continue with PhoneGap and try different methods for now, good luck!

**Comment by los3rz** [comment]
@RailKill Hi Nic, Can you verify if this method will work? Seems logical and possible to me though.

http://stackoverflow.com/questions/19498644/using-wordpress-for-authentication-in-jquery-mobile-phonegap-app

**Comment by RailKill** [comment]
Committed in **wc-rest** folder, getting WooCommerce data is done using a [PHP wrapper library by kloon](https://github.com/kloon/WooCommerce-REST-API-Client-Library). Refer to **orders.php** to see how to return list of orders. **All the ways to get different data such as products, etc. are commented in orders.php.**

To add/expose more methods, maybe can modify orders.php to take in a parameter so that can return different data depending on what the user wants -OR- put the API key in one location and create more .php scripts making use of the wrapper library.

**Comment by harytan** [comment]
Tested and proceed to #14
